verision: "3.8"

# Example local development stack

services:

  website:
    image: "node:latest" # https://hub.docker.com/_/node
    # React app hosted on webpack dev server or similar

  api:
    image: "node:latest" # https://hub.docker.com/_/node
    # JSON REST API hosted on express or similar

  secrets:
    image: "vault:latest" # https://hub.docker.com/_/vault
    cap_add:
      - "IPC_LOCK" # see docs

  database:
    image: "postgres:latest" # https://hub.docker.com/_/postgres

  cache:
    image: "redis:latest" # https://hub.docker.com/_/redis
