version: "3.8"

# Local development stack

services:

  website:
    build: "services/website"
    ports:
      - "3000:3000" # expose webserver to host machine
    tty: true # create-react-app dev server terminal magic

  api:
    build: "services/api"

  secrets:
    image: "vault:latest" # https://hub.docker.com/_/vault
    cap_add:
      - "IPC_LOCK" # see docs

  database:
    image: "postgres:latest" # https://hub.docker.com/_/postgres
