version: "3.8"

# Local development stack

services:

  website:
    build: "services/website"
    ports:
      - "3000:5000" # expose webserver to host machine
    volumes:
      - "./services/website/SnapShot/src:/SnapShot/src"
    environment:
      REACT_APP_API_URL: 'http://localhost:4000' # what the browser uses

  api:
    build: "services/api"
    ports:
      - "4000:4000"

  secrets:
    image: "vault:latest" # https://hub.docker.com/_/vault
    cap_add:
      - "IPC_LOCK" # see docs

  database:
    image: "postgres:latest" # https://hub.docker.com/_/postgres
