verision: "3.8"

# Local development stack

services:

  website:
    build: "services/website"

  api:
    build: "services/api"

  secrets:
    image: "vault:latest" # https://hub.docker.com/_/vault
    cap_add:
      - "IPC_LOCK" # see docs

  database:
    image: "postgres:latest" # https://hub.docker.com/_/postgres
