version: "3.8"

# Automated testing stack

services:

  website:
    image: "node:latest" # https://hub.docker.com/_/node
    # React app hosted on webpack dev server or similar

  api:
    image: "node:latest" # https://hub.docker.com/_/node
    # JSON REST API hosted on express or similar

  tests:
    image: "node:latest" # https://hub.docker.com/_/node
    # Cypress tests live here

  mocks:
    image: "bbyars/mountebank:latest" #https://hub.docker.com/r/bbyars/mountebank
    # Moutebank service imposters

networks:
  default:
    internal: true # no internet
