version: "3.8"

# Automated testing stack

services:

  website:
    build: "services/website"

  api:
    build: "services/api"

  cypress:
    image: "cypress/included:latest" # https://hub.docker.com/r/cypress/included/
    # https://github.com/cypress-io/cypress-docker-images
    # https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/

  mocks:
    image: "bbyars/mountebank:latest" #https://hub.docker.com/r/bbyars/mountebank
    # Moutebank service imposters

networks:
  default:
    internal: true # no internet
