version: "3.8"

# Automated testing stack

services:

  website:
    build: "services/website"

  api:
    build: "services/api"

  tests:
    build: "services/tests"

  mocks:
    image: "bbyars/mountebank:latest" #https://hub.docker.com/r/bbyars/mountebank
    # Moutebank service imposters

networks:
  default:
    internal: true # no internet
